version: "3.2"
services:
  nodejs-dwidget:
    container_name: dw-node
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/donate-widget

  mongodb-dwidget:
    container_name: dw-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
